extract_text:

  description: >
    Extract text from the given PDF file path.

  expected_output: >
    A structured text output from the PDF file path.

  agent: >
    pdf_extractor

analyze_invoice_text:

  description: >
      Given the extracted text from an invoice or bill and a user query,
      Analyze the content and provide an accurate, clear answer using knowledgebase.

  expected_output: >
      A precise HTML formatted answer to the {user_query} about the invoice or bill, based on the extracted content.
      Can add some inline css to improve readability.

  agent: invoice_analyzer